services:
  umodel-server:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile
    command: ["--addr", ":18080", "--data", "/data", "--graphstore", "file.memory"]
    ports:
      - "18080:18080"
    volumes:
      - umodel-data:/data

volumes:
  umodel-data: {}
